version: '3'
services:
  db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
    - db

networks: